export enum SettingApi {
  Get = 'Setting/Get',
  GetAllCities = 'Setting/GetAllCities',
  GetAllLabels = 'Setting/GetAllLabels',
  GetAllAreas = 'Setting/GetAllAreas',
  GetAllAreasPrices = 'Setting/GetAllAreaPrices',
  GetAllShopCategory = 'Setting/GetAllShopCategories',
  GetCustomerLinks = 'Setting/GetCustomerSupportLinks',
  GetAllCitiesWithAreas = 'Setting/GetAllCitiesWithAreas',
  Modify = 'Setting/Modify',
  UpsertCity = 'Setting/UpsertCity',
  UpsertLabel = 'Setting/UpsertLabel',
  UpsertArea = 'Setting/UpsertArea',
  UpsertCustomerLink = 'Setting/UpsertCustomerSupportLink',
  ModifyAreaPrice = 'Setting/ModifyAreaPrice',
  AddShopCategory = 'Setting/AddShopCategory',
  ModifyShopCategory = 'Setting/ModifyShopCategory',
  DeleteArea = 'Setting/DeleteArea',
  DeleteCity = 'Setting/DeleteCity',
  DeleteLabels = 'Setting/DeleteLabels',
  DeleteShopCategory = 'Setting/DeleteShopCategory',
}
